Unpin meson version in CI
It started causing problems with recent python versions:

```
RuntimeError: There is no current event loop in thread 'MainThread'.
```

when running tests